apiVersion: v1
entries:
  camping-backend-with-go:
  - apiVersion: v2
    appVersion: 1.22.5
    created: "2024-10-22T14:37:52.211932+09:00"
    description: A Helm chart for camping backend
    digest: 257aadf97ee03821dafda5a8c9ebd20d7d8581aee9b253eb0f6cea044989f9ca
    name: camping-backend-with-go
    type: application
    urls:
    - camping-backend-with-go-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.22.5
    created: "2024-10-22T14:37:52.21169+09:00"
    description: A Helm chart for camping backend
    digest: 40bf6720f88ca22b3658013e8a5fba1dafe3a5de4bb38fcdba5dee63906512d7
    name: camping-backend-with-go
    type: application
    urls:
    - camping-backend-with-go-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.22.5
    created: "2024-10-22T14:37:52.210431+09:00"
    description: A Helm chart for camping backend
    digest: 9d32ebe6ca4104e646a6654fe62c3a1314b9e79fb2fd5ef5dd25b610b00a85e3
    name: camping-backend-with-go
    type: application
    urls:
    - camping-backend-with-go-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.22.5
    created: "2024-10-22T14:37:52.209942+09:00"
    description: A Helm chart for camping backend
    digest: 6cbde70eac4f4fffb08664fbe5818de7b3fdb70879f8eb534d80ee1bdb9495bd
    name: camping-backend-with-go
    type: application
    urls:
    - camping-backend-with-go-1.0.0.tgz
    version: 1.0.0
  istio-gateway:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-22T14:37:52.21244+09:00"
    description: A Helm chart for istio-gateway
    digest: 37a77a366c7d83c844e5cd1e660b18f47c8e69335e17bc0679ec0207e2b67ad6
    name: istio-gateway
    type: application
    urls:
    - istio-gateway-1.0.0.tgz
    version: 1.0.0
  restframework:
  - apiVersion: v2
    appVersion: 5.1.2
    created: "2024-10-22T14:37:52.213614+09:00"
    description: A Helm chart for Kubernetes
    digest: 7ba6cf3cd8ca7af02056087a375f97d30320b788d507f79ff59531bb33e7ce05
    name: restframework
    type: application
    urls:
    - restframework-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 5.1.2
    created: "2024-10-22T14:37:52.213013+09:00"
    description: A Helm chart for Kubernetes
    digest: 056c03f4e5b4fbea6a4b149ff87e7f46047d4585b3f85e1ef098cbf728c0af54
    name: restframework
    type: application
    urls:
    - restframework-1.0.1.tgz
    version: 1.0.1
generated: "2024-10-22T14:37:52.209073+09:00"
