apiVersion: v1
entries:
  django-restframework:
  - apiVersion: v2
    appVersion: 5.1.2
    created: "2024-10-17T15:13:51.148794788Z"
    description: A Helm chart for Kubernetes
    digest: c55f08aae2c012a0b5e01be46aab494b77222690f9fd105ee7ca66b98b2cb353
    name: django-restframework
    type: application
    urls:
    - django-restframework-1.0.0.tgz
    version: 1.0.0
  istio-gateway:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-17T15:13:51.149355143Z"
    description: A Helm chart for istio-gateway
    digest: 37a77a366c7d83c844e5cd1e660b18f47c8e69335e17bc0679ec0207e2b67ad6
    name: istio-gateway
    type: application
    urls:
    - istio-gateway-1.0.0.tgz
    version: 1.0.0
generated: "2024-10-17T15:13:51.147011681Z"
